### ISSUE TITLE
Support ESP8266

### ISSUE THREAD

**Issue by sabag** [marcobrianza/ClickButton#4]
this library is awesome but it is not working on ESP8266. I was able to very easily fix it to work on ESP8266 by changing the code to :

  pinMode(_pin, INPUT_PULLUP);

instead of INPUT.

does this makes sense ? could this be pushed into the master ?

**Comment by marcobrianza** [comment]
look at this
https://github.com/marcobrianza/ClickButton/blob/master/ClickButton.cpp#L111
it already enables pullup in the correct case. I found it to work on ESP8266

**Comment by sabag** [comment]
ok so its probably something else because i tested it on wemos d1 mini and it did not work.

**Comment by marcobrianza** [comment]
some pins have external resistor connected to pins, for example try to use D1, D2, D5,D6,D7

**Comment by cstanke** [comment]
I can confirm that on ESP8266 based hardware with esp8266 Arduino Core 2.6.1, the code, as currently written, **does not** activate the internal pull-up on pull-up enabled pins.

The following code change works:
```
  //pinMode(_pin, INPUT);
  // Turn on internal pullup resistor if applicable
  //if (_activeHigh == LOW && internalPullup == CLICKBTN_PULLUP) digitalWrite(_pin,HIGH);
  if (_activeHigh == LOW && internalPullup == CLICKBTN_PULLUP)
    pinMode(_pin, INPUT_PULLUP);
  else
    pinMode(_pin, INPUT);
```

I've submitted [a pull request](https://github.com/marcobrianza/ClickButton/pull/5) with supporting documentation on this.

**Comment by marcobrianza** [comment]
hello, I just merged the pull requests about this issue
